# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# What combinations to test
environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 14

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile

test_script:
  - cmd: yarn run test

cache:
  - '%LOCALAPPDATA%/Yarn'                               # yarn cache
  - node_modules                                        # local npm modules
